language: node_js
node_js:
- node
addons:
  ssh_known_hosts: 137.99.3.8
before_deploy:
- openssl aes-256-cbc -K $encrypted_ad3ce4b387d1_key -iv $encrypted_ad3ce4b387d1_iv
  -in deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa
deploy:
  provider: script
  skip_cleanup: true
  script: sh ./deploy.sh
  on:
    branch: master